package com.yxw1268.fyp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OtpRecordAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtpRecordAllPropertiesEquals(OtpRecord expected, OtpRecord actual) {
        assertOtpRecordAutoGeneratedPropertiesEquals(expected, actual);
        assertOtpRecordAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtpRecordAllUpdatablePropertiesEquals(OtpRecord expected, OtpRecord actual) {
        assertOtpRecordUpdatableFieldsEquals(expected, actual);
        assertOtpRecordUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtpRecordAutoGeneratedPropertiesEquals(OtpRecord expected, OtpRecord actual) {
        assertThat(actual)
            .as("Verify OtpRecord auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtpRecordUpdatableFieldsEquals(OtpRecord expected, OtpRecord actual) {
        assertThat(actual)
            .as("Verify OtpRecord relevant properties")
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getOtpCode()).as("check otpCode").isEqualTo(expected.getOtpCode()))
            .satisfies(a -> assertThat(a.getExpiryTime()).as("check expiryTime").isEqualTo(expected.getExpiryTime()))
            .satisfies(a -> assertThat(a.getVerified()).as("check verified").isEqualTo(expected.getVerified()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOtpRecordUpdatableRelationshipsEquals(OtpRecord expected, OtpRecord actual) {
        // empty method
    }
}
