package com.yxw1268.fyp.domain;

import static com.yxw1268.fyp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProgressLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressLogAllPropertiesEquals(ProgressLog expected, ProgressLog actual) {
        assertProgressLogAutoGeneratedPropertiesEquals(expected, actual);
        assertProgressLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressLogAllUpdatablePropertiesEquals(ProgressLog expected, ProgressLog actual) {
        assertProgressLogUpdatableFieldsEquals(expected, actual);
        assertProgressLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressLogAutoGeneratedPropertiesEquals(ProgressLog expected, ProgressLog actual) {
        assertThat(actual)
            .as("Verify ProgressLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressLogUpdatableFieldsEquals(ProgressLog expected, ProgressLog actual) {
        assertThat(actual)
            .as("Verify ProgressLog relevant properties")
            .satisfies(a -> assertThat(a.getLogDate()).as("check logDate").isEqualTo(expected.getLogDate()))
            .satisfies(a ->
                assertThat(a.getWeightKg()).as("check weightKg").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getWeightKg())
            )
            .satisfies(a -> assertThat(a.getCompletedWorkout()).as("check completedWorkout").isEqualTo(expected.getCompletedWorkout()))
            .satisfies(a -> assertThat(a.getCaloriesIntake()).as("check caloriesIntake").isEqualTo(expected.getCaloriesIntake()))
            .satisfies(a -> assertThat(a.getSteps()).as("check steps").isEqualTo(expected.getSteps()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgressLogUpdatableRelationshipsEquals(ProgressLog expected, ProgressLog actual) {
        assertThat(actual)
            .as("Verify ProgressLog relationships")
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()))
            .satisfies(a -> assertThat(a.getPlan()).as("check plan").isEqualTo(expected.getPlan()));
    }
}
