package com.yxw1268.fyp.domain;

import static com.yxw1268.fyp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class UserProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileAllPropertiesEquals(UserProfile expected, UserProfile actual) {
        assertUserProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertUserProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileAllUpdatablePropertiesEquals(UserProfile expected, UserProfile actual) {
        assertUserProfileUpdatableFieldsEquals(expected, actual);
        assertUserProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileAutoGeneratedPropertiesEquals(UserProfile expected, UserProfile actual) {
        assertThat(actual)
            .as("Verify UserProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileUpdatableFieldsEquals(UserProfile expected, UserProfile actual) {
        assertThat(actual)
            .as("Verify UserProfile relevant properties")
            .satisfies(a -> assertThat(a.getAge()).as("check age").isEqualTo(expected.getAge()))
            .satisfies(a ->
                assertThat(a.getHeightCm()).as("check heightCm").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getHeightCm())
            )
            .satisfies(a ->
                assertThat(a.getWeightKg()).as("check weightKg").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getWeightKg())
            )
            .satisfies(a -> assertThat(a.getActivityLevel()).as("check activityLevel").isEqualTo(expected.getActivityLevel()))
            .satisfies(a -> assertThat(a.getGoal()).as("check goal").isEqualTo(expected.getGoal()))
            .satisfies(a -> assertThat(a.getDietPref()).as("check dietPref").isEqualTo(expected.getDietPref()))
            .satisfies(a -> assertThat(a.getMetabolicProfile()).as("check metabolicProfile").isEqualTo(expected.getMetabolicProfile()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserProfileUpdatableRelationshipsEquals(UserProfile expected, UserProfile actual) {
        // empty method
    }
}
